
package it.univaq.disim.bpd.businesstravelclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusinessTravel", targetNamespace = "http://businesstravel.bpd.disim.univaq.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BusinessTravel {


    /**
     * 
     * @param flightData
     * @param employee
     * @return
     *     returns it.univaq.disim.bpd.businesstravelclient.FlightConfirmation
     */
    @WebMethod(operationName = "TravelApproval")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TravelApproval", targetNamespace = "http://businesstravel.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.businesstravelclient.TravelApproval")
    @ResponseWrapper(localName = "TravelApprovalResponse", targetNamespace = "http://businesstravel.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.businesstravelclient.FlightTicketResponse")
    public FlightConfirmation travelApproval(
        @WebParam(name = "employee", targetNamespace = "")
        Employee employee,
        @WebParam(name = "flightData", targetNamespace = "")
        FlightData flightData);

}
