
package it.univaq.disim.bpd.businesstravelclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusinessTravelService", targetNamespace = "http://businesstravel.bpd.disim.univaq.it/", wsdlLocation = "file:/Users/massimotivoli/Development/workspace-jee-neon-1-BPD-c2/BusinessTravelClient/wsdl/businesstravel.wsdl")
public class BusinessTravelService
    extends Service
{

    private final static URL BUSINESSTRAVELSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSINESSTRAVELSERVICE_EXCEPTION;
    private final static QName BUSINESSTRAVELSERVICE_QNAME = new QName("http://businesstravel.bpd.disim.univaq.it/", "BusinessTravelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/massimotivoli/Development/workspace-jee-neon-1-BPD-c2/BusinessTravelClient/wsdl/businesstravel.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSTRAVELSERVICE_WSDL_LOCATION = url;
        BUSINESSTRAVELSERVICE_EXCEPTION = e;
    }

    public BusinessTravelService() {
        super(__getWsdlLocation(), BUSINESSTRAVELSERVICE_QNAME);
    }

    public BusinessTravelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSINESSTRAVELSERVICE_QNAME, features);
    }

    public BusinessTravelService(URL wsdlLocation) {
        super(wsdlLocation, BUSINESSTRAVELSERVICE_QNAME);
    }

    public BusinessTravelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSINESSTRAVELSERVICE_QNAME, features);
    }

    public BusinessTravelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessTravelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusinessTravel
     */
    @WebEndpoint(name = "BusinessTravelPort")
    public BusinessTravel getBusinessTravelPort() {
        return super.getPort(new QName("http://businesstravel.bpd.disim.univaq.it/", "BusinessTravelPort"), BusinessTravel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessTravel
     */
    @WebEndpoint(name = "BusinessTravelPort")
    public BusinessTravel getBusinessTravelPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://businesstravel.bpd.disim.univaq.it/", "BusinessTravelPort"), BusinessTravel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSTRAVELSERVICE_EXCEPTION!= null) {
            throw BUSINESSTRAVELSERVICE_EXCEPTION;
        }
        return BUSINESSTRAVELSERVICE_WSDL_LOCATION;
    }

}
