
package it.univaq.disim.bpd.etsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ETSInterface", targetNamespace = "http://etsservice.bpd.disim.univaq.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ETSInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.univaq.disim.bpd.etsclient.TravelClass
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "employTravelStatus", targetNamespace = "http://etsservice.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.etsclient.EmployTravelStatus")
    @ResponseWrapper(localName = "employTravelStatusResponse", targetNamespace = "http://etsservice.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.etsclient.EmployTravelStatusResponse")
    public TravelClass employTravelStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

}
