
package it.univaq.disim.bpd.etsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ETSServiceImplService", targetNamespace = "http://etsservice.bpd.disim.univaq.it/", wsdlLocation = "http://localhost:6060/ETSService/etsinterface?wsdl")
public class ETSServiceImplService
    extends Service
{

    private final static URL ETSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ETSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ETSSERVICEIMPLSERVICE_QNAME = new QName("http://etsservice.bpd.disim.univaq.it/", "ETSServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/ETSService/etsinterface?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ETSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ETSServiceImplService() {
        super(__getWsdlLocation(), ETSSERVICEIMPLSERVICE_QNAME);
    }

    public ETSServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ETSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ETSSERVICEIMPLSERVICE_QNAME);
    }

    public ETSServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ETSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ETSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ETSInterface
     */
    @WebEndpoint(name = "ETSServiceImplPort")
    public ETSInterface getETSServiceImplPort() {
        return super.getPort(new QName("http://etsservice.bpd.disim.univaq.it/", "ETSServiceImplPort"), ETSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ETSInterface
     */
    @WebEndpoint(name = "ETSServiceImplPort")
    public ETSInterface getETSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://etsservice.bpd.disim.univaq.it/", "ETSServiceImplPort"), ETSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ETSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ETSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ETSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
