
package it.univaq.disim.bpd.daclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DAInterface", targetNamespace = "http://daservice.bpd.disim.univaq.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DAInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.univaq.disim.bpd.daclient.FlightConfirmation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flightTicket", targetNamespace = "http://daservice.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.daclient.FlightTicket")
    @ResponseWrapper(localName = "flightTicketResponse", targetNamespace = "http://daservice.bpd.disim.univaq.it/", className = "it.univaq.disim.bpd.daclient.FlightTicketResponse")
    public FlightConfirmation flightTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        FlightData arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TravelClass arg1);

}
