
package it.univaq.disim.bpd.daclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DAServiceImplService", targetNamespace = "http://daservice.bpd.disim.univaq.it/", wsdlLocation = "http://localhost:6060/DAService/dainterface?wsdl")
public class DAServiceImplService
    extends Service
{

    private final static URL DASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DASERVICEIMPLSERVICE_QNAME = new QName("http://daservice.bpd.disim.univaq.it/", "DAServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/DAService/dainterface?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DAServiceImplService() {
        super(__getWsdlLocation(), DASERVICEIMPLSERVICE_QNAME);
    }

    public DAServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DASERVICEIMPLSERVICE_QNAME, features);
    }

    public DAServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DASERVICEIMPLSERVICE_QNAME);
    }

    public DAServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DASERVICEIMPLSERVICE_QNAME, features);
    }

    public DAServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DAServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DAInterface
     */
    @WebEndpoint(name = "DAServiceImplPort")
    public DAInterface getDAServiceImplPort() {
        return super.getPort(new QName("http://daservice.bpd.disim.univaq.it/", "DAServiceImplPort"), DAInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DAInterface
     */
    @WebEndpoint(name = "DAServiceImplPort")
    public DAInterface getDAServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://daservice.bpd.disim.univaq.it/", "DAServiceImplPort"), DAInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DASERVICEIMPLSERVICE_EXCEPTION;
        }
        return DASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
