
package it.univaq.disim.bpd.aaclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AAServiceImplService", targetNamespace = "http://aaservice.bpd.disim.univaq.it/", wsdlLocation = "http://localhost:6060/AAService/aainterface?wsdl")
public class AAServiceImplService
    extends Service
{

    private final static URL AASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AASERVICEIMPLSERVICE_QNAME = new QName("http://aaservice.bpd.disim.univaq.it/", "AAServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/AAService/aainterface?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AAServiceImplService() {
        super(__getWsdlLocation(), AASERVICEIMPLSERVICE_QNAME);
    }

    public AAServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AASERVICEIMPLSERVICE_QNAME, features);
    }

    public AAServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AASERVICEIMPLSERVICE_QNAME);
    }

    public AAServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AASERVICEIMPLSERVICE_QNAME, features);
    }

    public AAServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AAServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AAInterface
     */
    @WebEndpoint(name = "AAServiceImplPort")
    public AAInterface getAAServiceImplPort() {
        return super.getPort(new QName("http://aaservice.bpd.disim.univaq.it/", "AAServiceImplPort"), AAInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AAInterface
     */
    @WebEndpoint(name = "AAServiceImplPort")
    public AAInterface getAAServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://aaservice.bpd.disim.univaq.it/", "AAServiceImplPort"), AAInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AASERVICEIMPLSERVICE_EXCEPTION;
        }
        return AASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
